#
#   Copyright 2016 Walter Dolce
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
---
language: ruby
rvm:
  - 2.3.0

sudo: required
services:
  - docker

env:
  matrix:
    - SUITE=single-profile PLATFORM=opscode-centos-63-i386
    - SUITE=multiple-profiles PLATFORM=opscode-centos-63-i386
    - SUITE=noop PLATFORM=opscode-centos-63-i386
    - SUITE=single-profile PLATFORM=opscode-centos-63
    - SUITE=multiple-profiles PLATFORM=opscode-centos-63
    - SUITE=noop PLATFORM=opscode-centos-63
    - SUITE=single-profile PLATFORM=centos-64-i386
    - SUITE=multiple-profiles PLATFORM=centos-64-i386
    - SUITE=noop PLATFORM=centos-64-i386
    - SUITE=single-profile PLATFORM=centos-64
    - SUITE=multiple-profiles PLATFORM=centos-64
    - SUITE=noop PLATFORM=centos-64
    - SUITE=single-profile PLATFORM=centos-65-i386
    - SUITE=multiple-profiles PLATFORM=centos-65-i386
    - SUITE=noop PLATFORM=centos-65-i386
    - SUITE=single-profile PLATFORM=centos-65
    - SUITE=multiple-profiles PLATFORM=centos-65
    - SUITE=noop PLATFORM=centos-65
    - SUITE=single-profile PLATFORM=puppet-centos-66-32-puppet
    - SUITE=multiple-profiles PLATFORM=puppet-centos-66-32-puppet
    - SUITE=noop PLATFORM=puppet-centos-66-32-puppet
    - SUITE=single-profile PLATFORM=puppet-centos-66-64-puppet
    - SUITE=multiple-profiles PLATFORM=puppet-centos-66-64-puppet
    - SUITE=noop PLATFORM=puppet-centos-66-64-puppet
    - SUITE=single-profile PLATFORM=centos-67-i386
    - SUITE=multiple-profiles PLATFORM=centos-67-i386
    - SUITE=noop PLATFORM=centos-67-i386
    - SUITE=single-profile PLATFORM=centos-67
    - SUITE=multiple-profiles PLATFORM=centos-67
    - SUITE=noop PLATFORM=centos-67
    - SUITE=single-profile PLATFORM=centos-70
    - SUITE=multiple-profiles PLATFORM=centos-70
    - SUITE=noop PLATFORM=centos-70
    - SUITE=single-profile PLATFORM=centos-71
    - SUITE=multiple-profiles PLATFORM=centos-71
    - SUITE=noop PLATFORM=centos-71
    - SUITE=single-profile PLATFORM=centos-72
    - SUITE=multiple-profiles PLATFORM=centos-72
    - SUITE=noop PLATFORM=centos-72

before_install:
  - curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.9.0

install:
  - chef exec bundle install

before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
  - sudo iptables -L DOCKER || sudo iptables -N DOCKER

script:
  - chef exec bundle exec kitchen create ${SUITE}-${PLATFORM}
  - docker cp ${TRAVIS_BUILD_DIR}/test/fixtures ${SUITE}-${PLATFORM}:/tmp/fixtures
  - docker cp ${TRAVIS_BUILD_DIR}/test/integration ${SUITE}-${PLATFORM}:/tmp/integration
  - docker exec ${SUITE}-${PLATFORM} sh -c "source /tmp/integration/${SUITE}/cucumber/fixtures/provision_users"
  - chef exec bundle exec kitchen converge ${SUITE}-${PLATFORM}
  - chef exec bundle exec kitchen verify ${SUITE}-${PLATFORM}
  - chef exec bundle exec kitchen destroy ${SUITE}-${PLATFORM}
